---
- include: user.yml
  when: solr_create_user

- name: Set solr_filename for Solr 4+.
  set_fact:
    solr_filename: "solr-{{ solr_version }}"
  when: "solr_version.split('.')[0] >= '4'"

- name: Set solr_filename for Solr 3.x.
  set_fact:
    solr_filename: "apache-solr-{{ solr_version }}"
  when: "solr_version.split('.')[0] == '3'"

- name: Check if Solr has been installed already.
  stat:
    path: "{{ solr_install_path }}"
  register: solr_install_path_status

# Download
- include: download.yml
  when: solr_install_path_status.stat.isdir is not defined

# Install Solr < 5.
- include: install-pre5.yml
  when: solr_version.split('.')[0] < '5' and solr_install_path_status.stat.isdir is not defined

# Install Solr 5+.
- include: install.yml
  when: solr_version.split('.')[0] >= '5' and solr_install_path_status.stat.isdir is not defined

- name: Ensure solr is started and enabled on boot if configured.
  service:
    name: "{{ solr_service_name }}"
    state: "{{ solr_service_state }}"
    enabled: yes
  when: solr_service_manage

# Configure solr.
- include: configure.yml
  when: "solr_version.split('.')[0] >= '5'"

# Create cores, if any are configured.
- include: cores.yml
  when: "solr_cores and solr_version.split('.')[0] >= '5'"

- include: trim-fat.yml
  static: no
